services:
    clausi.tenefixes.listener:
        class: clausi\tenefixes\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @config
            - @auth
            - @request
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
